CREATE TABLE "GCG_5678_DDL_Values"(
 "ROW_NO" IDENTITY DEFAULT '0',
 "STAT_VALUE" CHAR(20),
 UNIQUE ("ROW_NO"));

CREATE TABLE "GCG_5678_SOLnNotes"(
 "ORDER_NO" CHAR(7),
 "RECORD_NO" CHAR(4),
 "Notes" LONGVARCHAR,
 "CREATE_USR" CHAR(8),
 "CREATE_DT" DATE,
 "LAST_CHG_USR" CHAR(8),
 "LAST_CHG_DT" DATE);

CREATE TABLE "GCG_5678_SOLnStat"(
 "ORDER_NO" CHAR(7),
 "RECORD_NO" CHAR(4),
 "LINE_STAT" CHAR(100),
 "CREATE_USR" CHAR(8),
 "CREATE_DT" DATE,
 "LAST_CHG_USR" CHAR(8),
 "LAST_CHG_DT" DATE);
